### ISSUE TITLE
.genesis_deps contains safe dep but safe not in starkandwayne/concourse container

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/bosh-deployment#5]
this leads to errors when trying to deploy this via a genesis managed pipeline

**Comment by jhunt** [comment]
Updated the concourse image to include safe 0.0.26, and then promoted that rc to latest.

Care to give it another go?

**Comment by bodymindarts** [comment]
I can give it a try

**Comment by jhunt** [comment]
@bodymindarts did that try ever pan out?
